'use client'

import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'

const backToHome: Record<string, string> = {
  en: 'Back to Home', ro: 'Înapoi la Pagina Principală', de: 'Zurück zur Startseite',
  fr: "Retour à l'accueil", it: 'Torna alla Home', es: 'Volver al inicio',
  pl: 'Wróć do strony głównej', nl: 'Terug naar Home', pt: 'Voltar ao início',
  cs: 'Zpět na úvodní stránku', hu: 'Vissza a főoldalra', sv: 'Tillbaka till startsidan',
  da: 'Tilbage til forsiden', fi: 'Takaisin etusivulle', no: 'Tilbake til forsiden',
}

export default function TermsPage() {
  const { locale } = useLanguage()
  const updated = 'May 19, 2025'
  const backLabel = backToHome[locale] ?? backToHome.en

  return (
    <div className="pt-24 pb-24 min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

        <div className="mb-10">
          <Link href={`/${locale}`} className="inline-flex items-center gap-2 h-10 px-4 text-[14px] font-medium border border-[#E8E8E8] rounded-xl hover:border-[#F36D21] hover:text-[#F36D21] text-[#545554] transition-all duration-200">
            <ArrowLeft size={15} />
            {backLabel}
          </Link>
        </div>

        <h1 className="mb-2">Terms of Use</h1>
        <p className="text-[14px] text-[#888] mb-12">Last updated: {updated}</p>

        <div className="prose prose-gray max-w-none space-y-10 text-[15px] text-[#545554] leading-[1.8]">

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Robobist website at <strong>robobist.com</strong> ("Website"), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Website. These terms apply to all visitors, including potential customers, partners, and business representatives.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">2. Who We Are</h2>
            <p>
              Robobist ("<strong>we</strong>", "<strong>us</strong>", "<strong>our</strong>") is a robotics company with operations in Germany and Romania, European Union. We develop and distribute autonomous pallet truck solutions for warehouses across Europe. For enquiries: <a href="mailto:contact@robobist.com" className="text-[#F36D21] hover:underline">contact@robobist.com</a>
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">3. Use of the Website</h2>
            <p>You may use this Website for lawful purposes only. You agree not to:</p>
            <ul className="mt-3 space-y-2 list-none pl-0">
              {[
                'Use the Website in any way that violates applicable laws or regulations',
                'Attempt to gain unauthorised access to any part of our systems or infrastructure',
                'Transmit any unsolicited or unauthorised advertising or promotional material',
                'Scrape, harvest, or systematically extract data from the Website without our written consent',
                'Misrepresent your identity or affiliation when submitting enquiries or form data',
              ].map(item => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-[#F36D21] mt-1 flex-shrink-0">—</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">4. Intellectual Property</h2>
            <p>
              All content on this Website, including text, images, graphics, logos, product descriptions, and technical specifications, is the property of Robobist or its licensors and is protected by applicable intellectual property laws.
            </p>
            <p className="mt-3">
              You may not reproduce, distribute, modify, or create derivative works from any content on this Website without our prior written permission. Viewing and printing content for personal, non-commercial reference is permitted.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">5. Product Information & Pricing</h2>
            <p>
              Product specifications, prices, and availability displayed on this Website are for informational purposes and are subject to change without notice. The price estimates generated by our Configurator tool are indicative only. Final pricing is confirmed in a formal written quotation issued by Robobist following a consultation.
            </p>
            <p className="mt-3">
              We make every effort to ensure accuracy, but we do not warrant that product descriptions or pricing information are error-free, complete, or current.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">6. Disclaimer of Warranties</h2>
            <p>
              This Website is provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Website will be uninterrupted, error-free, or free of viruses.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">7. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Robobist shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of, or inability to use, this Website. Our total liability for any claim arising from your use of the Website shall not exceed €100.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">8. Third-Party Links</h2>
            <p>
              This Website may contain links to third-party websites. These links are provided for convenience only. We have no control over, and assume no responsibility for, the content or practices of any third-party websites. Accessing linked sites is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">9. Governing Law</h2>
            <p>
              These Terms of Use are governed by and construed in accordance with the laws of Romania and applicable European Union law. Any disputes arising from these terms or your use of the Website shall be subject to the exclusive jurisdiction of the courts of Romania, without prejudice to your rights as an EU consumer.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">10. Changes to These Terms</h2>
            <p>
              We may update these Terms of Use from time to time. The "Last updated" date at the top of this page reflects the most recent revision. Continued use of our Website after changes constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-[20px] font-semibold text-black mb-3">11. Contact</h2>
            <p>
              For any questions regarding these Terms of Use:{' '}
              <a href="mailto:contact@robobist.com" className="text-[#F36D21] hover:underline">contact@robobist.com</a>
            </p>
          </section>

        </div>

        <div className="mt-14 pt-8 border-t border-[#E8E8E8]">
          <Link href={`/${locale}`} className="inline-flex items-center gap-2 h-10 px-4 text-[14px] font-medium border border-[#E8E8E8] rounded-xl hover:border-[#F36D21] hover:text-[#F36D21] text-[#545554] transition-all duration-200">
            <ArrowLeft size={15} />
            {backLabel}
          </Link>
        </div>

      </div>
    </div>
  )
}
